name: Douyin Bond Maintainer

on:
  schedule:
    - cron: '0 5 * * *'  # 每天 UTC 5:00，即北京时间 13:00
  workflow_dispatch:

jobs:
  bond:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        user: [1, 2, 3, 4]   # 四个用户

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install chromium

      - name: Store cookies into file
        run: echo "${{ secrets.COOKIES }}" | base64 --decode > cookies.json

      - name: Set environment variables
        run: |
          echo "NICKNAME=${{ secrets['NICKNAME_' + matrix.user] }}" >> $GITHUB_ENV
          echo "MSG=${{ secrets['MSG'] }}" >> $GITHUB_ENV
          echo "PROXY=${{ secrets.PROXY }}" >> $GITHUB_ENV

      - name: Run Douyin Bond Maintainer
        run: python main.py

      - name: Upload error screenshot
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error-screenshot-${{ matrix.user }}
          path: error.png
